# POST register
POST  http://localhost:3001/api/users/register
content-type: application/json

{
  "email": "YulyaFed86@gmail.com",
  "password": "123456789"
}
###

# POST login
# @name login
POST http://localhost:3001/api/users/login
content-type: application/json

{
  "email": "test9@gmail.com",
  "password": "123456789"
}
###

@token = Bearer {{login.response.body.token}}

# POST logout
POST http://localhost:3001/api/users/logout
Authorization: {{token}}
###

# Get currentUser
GET http://localhost:3001/api/users/current
Authorization: {{token}}
###

# PATCH UploadAvatar
PATCH http://localhost:3001/api/users/avatars
Content-Type: multipart/form-data; boundary=FormBoundary
Authorization: {{token}}

--FormBoundary
Content-Disposition: form-data; name="avatar"; filename="mountains-g4a6e528e0_640.jpg"
Content-Type: image/jpeg

< /home/yulya/Downloads/mountains-g4a6e528e0_640.jpg
--FormBoundary--
###

# POST register
POST  http://localhost:3001/api/users/register
content-type: application/json

{
  "email": "test_yfe@mailinator.com",
  "password": "123456789"
}
###

# Get verification
GET  http://localhost:3001/api/users/verify/234242
###

# Post message of verification
POST   http://localhost:3001/api/users/verify
content-type: application/json

{
  "email": "test_yfe@mailinator.com"
}
###
