# Get Contacts
GET http://localhost:3001/api/contacts
###

# Get Contact by id
GET http://localhost:3001/api/contacts/63c5511c40c9da2231ec1304
###

# Post Contact 
POST http://localhost:3001/api/contacts
content-type: application/json

{
"name": "Anna",
"email": "1@gmail.com",
"phone": "(098) 689-4566",
"favorite": true
}
###

# Delete Contact 
DELETE http://localhost:3001/api/contacts/63c5511c40c9da2231ec1304
###

# Put Contact
PUT http://localhost:3001/api/contacts/63c5517640c9da2231ec1308
content-type: application/json

{
"name": "Ivanf",
"email": "2@gmail.com",
"phone": "(098) 777-4588"
}
###