# POST register
POST  http://localhost:3001/api/users/register
content-type: application/json

{
  "email": "test8@gmail.com",
  "password": "123456789"
}
###

# POST login
# @name login
POST http://localhost:3001/api/users/login
content-type: application/json

{
  "email": "test8@gmail.com",
  "password": "123456789"
}
###

@token = Bearer {{login.response.body.token}}

# POST logout
POST http://localhost:3001/api/users/logout
Authorization: {{token}}
###

# Get currentUser
GET http://localhost:3001/api/users/current
Authorization: {{token}}
###

# PATCH UploadAvatar
PATCH http://localhost:3001/api/users/public/avatars
Content-Type: multipart/form-data
Authorization: {{token}}
{
  "avatarURL": "www.gravatar.com/avatar/129adcf96ff3e4667ea64a693e44a377"
}

###

